stare:
  description: A 60-second zenith stare.
  integration_time: 60
  scan_pattern: stare
  pointing_frame: az_el
  scan_center: [0, 90]
  pointing_units: degrees
  sample_rate: 20

daisy:
  description: 'A daisy scan with a 2-degree radius.'
  pointing_frame: ra_dec
  pointing_units: degrees
  scan_pattern: daisy_miss_center
  scan_center: [150., 10]
  sample_rate: 50
  scan_options:
    radius: 2
    speed: 0.5
    petals: 2.11
    miss_factor: 0.1

back_and_forth:
  description: ''
  start_time: '2022-07-01T08:00:00'
  integration_time: 60
  scan_pattern: back_and_forth
  scan_center: [45, 45]
  pointing_frame: az_el
  pointing_units: degrees
  sample_rate: 20
  scan_options:
    x_throw: 5
    y_throw: 0
    speed: 0.5
